### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by francoism90** [francoism90/mediadb#1]
- [ ] Upload using browser. Import is support by: `artisan media:import /path/to/import <user-id>`
- [ ] Playlists
- [ ] Recommendations (based on media seen, random, searches, etc.?)
- [ ] Subscribe
- [ ] Likes (https://github.com/cybercog/laravel-love)
- [ ] IMDB/TV API's integration
- [ ] Improve player (settings, etc.)
